Loops
kSenfelds/c-sharp-syllabus pull request #4
Opened 2023-02-21 10:18 UTC by kSenfelds

Loops exercises done

2023-02-22 20:48 UTC, ausmoons requested changes

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/AsciiFigure/AsciiFigure.cs
> +        private const int slash1 = 47;
var bez private const, jo šis ir iekšā metodē, Pieriek ar var slash2 = 92;

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/AsciiFigure/Program.cs
> +           AsciiFigure ascii = new AsciiFigure();
space nav ok, 4 space jeb 1 tab

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 10/NumberSquare.cs
> +        public void createNumberSquare ()
Metodes nosaukumi ar lielo burtu

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 10/NumberSquare.cs
> +        public void createNumberSquare ()
CreateNumberSquare()

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 10/NumberSquare.cs
> +
Liekas tukšas rindas nevajag atstāt

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 6/FizzBuzz.cs
> +
Pārbaudi visur tukšās rindas

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 9/Program.cs
> +           RollTwoDice roll = new RollTwoDice();
Tab nav ok

2023-02-22 20:48 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise4/Program.cs
> +            {
Sakārto visos failos space

2023-02-24 16:25 UTC, EdgarsSalmins commented on csharp-basics/exercises/Loops/Loops/Exercise4/Program.cs
> +            }
starp loopiem viena tukša rinda

2023-02-24 16:25 UTC, EdgarsSalmins approved these changes

2023-02-24 17:31 UTC, merged