Polymorphism
kSenfelds/c-sharp-syllabus pull request #8
Opened 2023-03-11 11:17 UTC by kSenfelds

Polymorphism exercises done

2023-03-12 12:43 UTC, ausmoons requested changes

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRace/Toyota.cs
> +        private int currentSpeed = 0;
_currentSpeed

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRace/Volkswagen.cs
> +        private int currentSpeed = 0;
_currentSpeed

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public int _foodEaten { get; private set; }
FoodEaten.. šis ir public

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public abstract void makeSound();
Metodes ar lielo burtu

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Hierarchy/Cat.cs
> +        public override void makeSound()
Metodes ar lielo burtu

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Money.cs
> +        public override string ToString()
Starp metodēm tukša rinda

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Product.cs
> +            return Available > 0;
Availible ir kosntruktorā un tad tad vēl ir public un var izmainīt Availible caur public void DecreaseCount(). Man nešķiet šis pareizi @EdgarsSalmins.

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                    case '1': Console.WriteLine(machine1); break;
Sakāro jaunās rindas šeit

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                            Console.WriteLine("Press 3 to stop");
case "1" :
case "2": userMoney.Euros += int.Parse(coin); break;

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                            Console.WriteLine("Press 3 to stop");
un sakārto break jaunā rindā visur

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                                case "0.20": userMoney.Cents += 20; break;
Tev būtu jāuzraksta tā, lai na jāraksta katram gadījumam atsevišķi 0.5 un 50. Kaut vai metodi, kas pati pareizina ar 10

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +        private Money _change = new Money();
Kāpēc tev vajag 2 propertijus vēl ar Money?

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +            Amount = _total;
Kas te notiek.. 
  _total.Cents += amount.Cents;
  var change = _total.Cents % 100;
 _total.Cents = change;

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +                    DeleteAmounts();
Kāpēc te būtu jābūt deleteAmount..es sagaidītu, ka pie update tiktu samazināts tikai money, name vai price

2023-03-12 12:43 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +                if (selectedProduct.CanAfford(Amount))
if (selectedProduct.CanAfford(Amount)) būtu jābūt pirms metode UpdateProduct(int productNumber, string name, Money? price, int amount) tiek izsaukta

2023-03-15 20:34 UTC, ausmoons requested changes

2023-03-15 20:34 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                                    break;
Neredzu, kur apvienotu vienādo loģiku iekš case -> case "1" :
case "2": userMoney.Euros += int.Parse(coin); break;

2023-03-15 20:34 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +            Amount = moneyInMachine;
Tu šeit ar vienu reizi nomaini visu esošo amount. Tu nevari pievienot papildus, bet vari tikai ielikt monētas ar vienu reizi?

2023-03-15 20:34 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +            Amount = moneyInMachine;
Tev būtu jāpievieno jaunais amount pie moneyInMachine. moneyInMachine es sagaidītu, ka ir private mainīģais, nevis tikko deklarēts 25 rindiņā.

2023-03-23 07:15 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +            Amount = moneyInMachine;
te viss ok... saskaita iemesto naudu ar jau esošo.... saformatē valīdu naudas daudzumu.. un piešķir atpakaļ Amount... 
te viss ok.

2023-03-23 07:23 UTC, EdgarsSalmins approved these changes

2023-03-23 07:33 UTC, merged